sudo: required
dist: trusty
language: ruby
rvm:
  - 2.5
script:
  - bundle install
  - gem build kurgan.gemspec
  - gem install kurgan-*.gem
  - kurgan help
deploy:
  provider: rubygems
  api_key: "${RUBYGEMS_API_KEY}"
  gem: kurgan
  on:
   all_branches: true
   condition: $TRAVIS_BRANCH =~ ^develop|master &&  $TRAVIS_EVENT_TYPE =~ ^push|api$ && $TRAVIS_REPO_SLUG == "theonestack/kurgan"
